Add optional repeat query parameter to repeat commands.
maddox/harmony-api pull request #43
Opened 2016-11-28 17:32 UTC by farooqu

This adds the ability to specify an optional repeat query for command POSTS which will issue that command that number of times.

2016-11-28 17:32 UTC, farooqu commented
I know nothing about MQTT so wasn't sure of how to implement this with it, as a result I only did this for HTTP.

2016-11-28 17:34 UTC, maddox commented
Why not just multiple requests?

2016-11-28 18:20 UTC, farooqu commented
The use case I had in mind was for volume controls with Amazon Alexa/Google Home. It's awkward to have to say "turn the volume up", "turn the volume up", "turn the volume up". So you can setup "turn volume up" to make one request which specifies the number of times you want it to go up. Likewise, you can say something like "turn volume up 5 times" and still issue the request one time, but with repeat as 5.

2016-11-28 18:22 UTC, maddox commented
> The use case I had in mind was for volume controls with Amazon Alexa/Google Home. It's awkward to have to say "turn the volume up", "turn the volume up", "turn the volume up".

lmao, what's wrong with that? That should only take about 45 seconds to accomplish.

Ok, lets figure out what the mqtt version of this looks like. I think this came up in the past. We could do some sort of serialized message I guess. Separated by a `|` or something? Would love to hear some ideas.

2016-11-29 15:14 UTC, farooqu commented
I think just having an optional ":repeatInt" following the command name should do the trick. That way we can split on ':', and we'll always get the command name as the first index, and either the repeat int, or undefined as the second index and we can treat that just like the ?repeat= request query.

2016-11-29 15:25 UTC, maddox commented
This is good, I like that. It feels real nice, just a count specifier for the command name. Love it.

2016-11-29 15:27 UTC, maddox requested changes

2016-11-29 15:27 UTC, maddox commented on README.md
> +    POST /hubs/:hub_slug/devices/:device_slug/commands/:command_slug/?repeat=3 => {message: "ok"}
these shouldn't have slashes at the end:

    POST /hubs/:hub_slug/devices/:device_slug/commands/:command_slug?repeat=3 => {message: "ok"}

2016-11-29 15:27 UTC, maddox commented
Have you tested this, does it work well without any pause between sending the commands?

2016-11-29 16:00 UTC, farooqu commented
I've tested the HTTP implementation, and use it with volume-up and volume-down, work's pretty nicely.

2016-11-29 16:13 UTC, farooqu commented
I squashed all of the commits and merges into one.

2016-11-29 16:52 UTC, maddox approved these changes

2016-11-29 16:52 UTC, merged